# Generated by Django 5.1.4 on 2025-01-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_hashed_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hashed_password',
            field=models.CharField(max_length=300),
        ),
    ]
