# Generated by Django 5.1.4 on 2025-01-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
